@echo off
title GuardiaPass Neural Engine
echo [SHIELD] Initializing Quantum-Resistant Vault...
echo [SHIELD] Verifying Neural Core Dependencies...
call npm install
echo [SHIELD] Launching Security Environment...
set GEMINI_API_KEY=YOUR_API_KEY_HERE
npm run dev
